thomaspark/flexboxfroggy

levels.js

Missing word, added. :)
(amazing little project by the way!)

Missing word

---

js/docs.js
js/levels.js
lang/pt-br/index.html

Hi, I just finished the translation. This is my first PR, let me know if I made any mistake.

Add Brazilian Portuguese translation

---

js/docs.js
js/levels.js
lang/de/index.html

This pull request includes the German translation.
This is **work in progress**, so don't merge right away.
The level strings are missing. I will update this as soon as possible.

German translation

---

index.html
js/levels.js
js/messages.js
lang/de/index.html

Add missing translations of new strings.
Remove superfluous comma.
Write _German_ ... in German. ;)
Fix #24.

Translate new strings.

---

js/messages.js

Add new Portuguese translations as seen in #25

Add translations in pt-br

---

js/game.js

I think this is a nice change because it uses less code and also, it is being used in other parts of this same file, such as the first line: `var lang = lang || 'en';`

Use short-circuit evaluation instead of if

---

index.html
js/game.js

edit index.html and js/game.js to import the Firebase library and to log data in the Firebase database.

Tweaks for using Firebase

---

index.html

This is the recommended way now, and the default Google provide.

Always load Analytics over HTTPS

---

index.html
js/game.js

Deprecates Firebase and imports Parse in `index.html` and `game.js`

modifies index.html and game.js to collect user logs in Parse

---

js/docs.js

Fix a word

---

js/game.js

Same as https://github.com/thomaspark/gridgarden/pull/61  🥕

Automatically switch language if not specified

---

index.html
js/game.js

Deprecate 1) importing the Parse library in `index.html` and 2) corresponding code in `js/game.js`

Deprecate game logging

---

js/levels.js
js/messages.js

Saw the settings update and decided to add Latvian translation right away. While playing through to recheck my previous translation, found that some more errors and fixed them as well.

Add Latvian translation for messages fix level translation

---

css/style.css
index.html
js/native.js

The ad unit is provided by Carbon/BuySellAds. The ad unit is installed in the
footer.

Integrate Native by BuySellAds

---

js/game.js

* Add `tada` animation to next button on correct input
* Add `disabled` state to next button as soon as
input is entered to faster detect change from
correct to incorrect state.

Add `tada` animation to next button on correct input

---

css/style.css

The application is great but when we open it on a cell phone it is a bit annoying to write the code and have to scroll horizontally to see the frog's changes.
I made a small change, for small screens the frog will be below the most accessible code in sight.
I hope this change works for you or that you consider modifying it in another way.
Greetings and congratulations on the project!

A little visual change for mobile

---

css/style.css

Improves contrast between text and background in editor pane, main body, and footer

Improve contrast

---

js/game.js

Fix win screen translating

---

js/levels.js

"Using" → "Use"
There are other ways to fix this, but this one seemed the simplest.
Thanks for the great game! 🐸

Fix english typo

---

js/messages.js

Added missing Ukrainian translations

Add missing Ukrainian translations

---

js/levels.js

fix: clarify clicking is necessary to show possible values, not hover
